### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [BigSpider-Dev/jogo_da_velha#2]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by BigSpider-Dev** [comment]
Opa
Tudo bom?
Comecei fiz ele nas minhas férias no meio do ano passado, com a intenção de
ir evoluindo, mas ando ocupado, porém se quiseres podemos ver o que tem em
mente.
Abraço


Em qua., 1 de fev. de 2023 13:33, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Oi BigSpider-Dev.

> Opa
> Tudo bom?
> Comecei fiz ele nas minhas férias no meio do ano passado, com a intenção de ir evoluindo, mas ando ocupado, porém se quiseres podemos ver o que tem em mente.
> Abraço

opa mano, valeu pelo teu contato. queria contribuir com esse jogo aí. vou fechar a issue já que respondeu minha dúvida.
